name: Continuous Integration

on: [push]

jobs:
  ubuntu-latest:
    name: Ubuntu Latest
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ '3.5', '3.6', '3.7', '3.8' ]

    steps:
    - uses: actions/checkout@v2
      name: Checkout the repository
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
        architecture: x64
    - name: Install Python dependencies
      run: python -m pip install ruamel.yaml cython scons
    - name: Build Cantera
      run: python3 `which scons` build
